#!/usr/bin/env python3
"""
Script to concatenate all project-overview documents into PROJECT_OVERVIEW.md
"""

import os
from pathlib import Path

def main():
    # Define paths
    project_overview_dir = Path("/home/ubuntu/alphadataomega/docs/project-overview")
    output_file = Path("/home/ubuntu/alphadataomega/PROJECT_OVERVIEW.md")
    
    # Get all markdown files and sort them numerically
    md_files = sorted([f for f in project_overview_dir.glob("*.md") if f.name.startswith(('0', '1', '2'))])
    
    print(f"Found {len(md_files)} project overview files to concatenate:")
    for file in md_files:
        print(f"  - {file.name}")
    
    # Create the concatenated content
    concatenated_content = []
    
    # Add header
    concatenated_content.append("# AlphaDataOmega (ADO) & TRN Platform - Complete Project Overview")
    concatenated_content.append("")
    concatenated_content.append("*This document is automatically generated by concatenating all project overview sections.*")
    concatenated_content.append("")
    concatenated_content.append("---")
    concatenated_content.append("")
    
    # Process each file
    for i, file_path in enumerate(md_files, 1):
        print(f"Processing {file_path.name}...")
        
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read().strip()
        
        # Add section separator
        concatenated_content.append(f"<!-- ===== SECTION {i:02d}: {file_path.stem} ===== -->")
        concatenated_content.append("")
        
        # Add the content
        concatenated_content.append(content)
        concatenated_content.append("")
        concatenated_content.append("---")
        concatenated_content.append("")
    
    # Write the concatenated file
    final_content = "\n".join(concatenated_content)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(final_content)
    
    print(f"\nSuccessfully created {output_file}")
    print(f"Total lines: {len(final_content.splitlines())}")
    print(f"Total characters: {len(final_content)}")

if __name__ == "__main__":
    main()